# https://github.com/operator-framework/operator-lifecycle-manager/blob/master/deploy/upstream/quickstart/crds.yaml#L207
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    crd/fake: "true"
  name: clusterserviceversions.operators.coreos.com
spec:
  group: operators.coreos.com
  names:
    kind: ClusterServiceVersion
    listKind: ClusterServiceVersionList
    plural: clusterserviceversions
    shortNames:
      - csv
      - csvs
    singular: clusterserviceversion
  scope: Namespaced
  versions:
    - name: v1alpha1
      # oc get csv -n redhat-ods-operator | grep "rhods-operator" | awk -F ' {2,}' '{print $3}'
      additionalPrinterColumns:
      - description: The name of the CSV
        jsonPath: .spec.displayName
        name: Display
        type: string
      - description: The version of the CSV
        jsonPath: .spec.version
        name: Version
        type: string
      - description: The name of a CSV that this one replaces
        jsonPath: .spec.replaces
        name: Replaces
        type: string
      - jsonPath: .status.phase
        name: Phase
        type: string
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
