---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    crd/fake: "true"
  name: consolelinks.console.openshift.io
spec:
  group: console.openshift.io
  names:
    kind: ConsoleLink
    listKind: ConsoleLinkList
    singular: consolelink
    plural: consolelinks
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
