---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    crd/fake: "true"
  name: dscinitializations.dscinitialization.opendatahub.io
spec:
  group: dscinitialization.opendatahub.io
  names:
    plural: dscinitializations
    singular: dscinitialization
    shortNames:
      - dsci
    kind: DSCInitialization
    listKind: DSCInitializationList
  scope: Cluster
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
