# here's a quite nice doc page for browsing CRDs:
# https://kubespec.dev/kyverno/kyverno.io/v2beta1/ClusterPolicy
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - route.yaml
  - servicemonitor.yaml
  - consolelink.yaml
  - dsc.yaml
  - dsci.yaml
  - imagestream.yaml
  - buildconfig.yaml
  - clusterserviceversion.yaml
  - components.platform.opendatahub.io_dashboards.yaml
#  - servingruntime.yaml
#  - inferenceservice.yaml
#  - auth.yaml
