on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  rhoai-in-kind:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Kubernetes KinD Cluster
        uses: helm/kind-action@v1
        with:
          version: v0.27.0
          cluster_name: kind

      - name: Install ArgoCD
        run: |
          kubectl create -k components/01-argocd
          kubectl wait --for=condition=Ready pod -l app.kubernetes.io/name=argocd-server -n argocd --timeout=120s

      - name: Install Kyverno
        run: |
          kubectl create -k components/02-kyverno
          kubectl wait --for=condition=Ready pod -l app.kubernetes.io/name=kyverno -n kyverno --timeout=120s

      - name: Deploy fake CRDs
        run: kubectl apply -k components/crds

      - run: kubectl create namespace redhat-ods-applications

      - name: Install KF Pipelines
        run: |
          kubectl create namespace redhat-ods-applications
          kubectl apply -f components/03-kf-pipelines.yaml
          
          PASSWORD=$(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d)
          export ARGOCD_OPTS='--insecure --port-forward --port-forward-namespace argocd'
          argocd login --insecure --username admin --password $PASSWORD
          argocd cluster add kind-kind --core --yes
          argocd app sync kf-pipelines
          
          # wait for argocd to sync the application!
          #kubectl wait --for=condition=Ready pod -l app.kubernetes.io/name=controller-manager -n redhat-ods-applications --timeout=120s
