on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  rhoai-in-kind:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: red-hat-data-services/ods-ci
          ref: master
          path: ods-ci

      - name: Kubernetes KinD Cluster
        uses: helm/kind-action@v1
        with:
          version: v0.27.0
          # Dashboard tests fail on k8s 1.32
          # https://hub.docker.com/r/kindest/node/tags
          # Let's keep using same version as for dashboard then
          node_image: "docker.io/kindest/node:v1.31.6"
          cluster_name: kind
          config: components/00-kind-cluster.yaml

      - name: Deploy stuff into Kubernetes
        run: python3 components/deploy.py

      # https://docs.astral.sh/uv/guides/integration/github/#installation
      # https://github.com/astral-sh/setup-uv
      - name: Install Poetry
        run: |
          pipx ensurepath
          pipx install poetry

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: poetry
          cache-dependency-path: "ods-ci/poetry.lock"

      - name: "Set up faked openshift oauth for oc client"
        run: |
          set -Eeuxo pipefail
          oc apply -f components/opendatahub-tests/openldap.yaml
          pushd components/opendatahub-tests/nginx_certs
          ./gen.sh
          popd
          nginx -c "${PWD}/components/opendatahub-tests/nginx.conf" &
          while ! nc -z 127.0.0.1 8443; do sleep 1; done
          oc login --insecure-skip-tls-verify=true -u htpasswd-cluster-admin-user -p password 127.0.0.1:8443

      - name: Run ods-ci tests
        run: |
          set -Eeuxo pipefail
          ods_ci/run_robot_test.sh --skip-oclogin=true --test-variables-file=${{ github.workspace }}/ods-ci/test-variables.yml --extra-robot-args='-e AutomationBug -e ProductBug -e Dashboard -e deprecatedTest -e ExcludeOnRHOAI ods-ci/ods_ci/tests/Tests/0500__ide/0501__ide_jupyterhub/test-minimal-image.robot'
        working-directory: ods-ci
