on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  rhoai-in-kind:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Kubernetes KinD Cluster
        uses: helm/kind-action@v1
        with:
          version: v0.27.0
          cluster_name: kind

      - name: Install ArgoCD
        run: |
          kubectl apply -k components/01-argocd
          kubectl wait --for=condition=Ready pod -l app.kubernetes.io/name=argocd-server -n argocd --timeout=120s

      - name: Install Kyverno
        run: |
          kubectl apply -k components/02-kyverno
          kubectl wait --for=condition=Ready pod -l app.kubernetes.io/name=kyverno -n kyverno --timeout=120s

      - name: Deploy fake CRDs
        run: kubectl apply -k components/crds
