apiVersion: v1
kind: Pod
metadata:
  name: kerneltest
  namespace: default
spec:
  restartPolicy: Never
  containers:
  - name: t
    image: quay.io/opendatahub/odh-pipeline-runtime-datascience-cpu-py312-ubi9:2025b-v1.36
    imagePullPolicy: IfNotPresent
    command: ["sleep", "1200"]
